In [1]:
import nltk
from nltk import word_tokenize
import re
from nltk.corpus import stopwords 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from nltk.stem import PorterStemmer, LancasterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from nltk import word_tokenize,sent_tokenize
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

## Read the Dataset

In [2]:
df=pd.read_csv('Downloads\\amazon_alexa.csv')

In [3]:
df.head()

reviews  sentiment
0                                      Love my Echo!          1
1                                          Loved it!          1
2  Sometimes while playing a game, you can answer...          1
3  I have had a lot of fun with this thing. My 4 ...          1
4                                              Music          1

## Handling NULL Values(If any)

In [4]:
df.isnull().sum()

reviews      0
sentiment    0
dtype: int64

In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [6]:
sw = stopwords.words('English')

In [7]:
lm = WordNetLemmatizer()

In [8]:
data = []
for i in df['reviews']:
    t = i.lower()                                  # lower case conversion
    t = re.sub('[^A-Za-z]',' ',t)                  # removing punctuation
    t = word_tokenize(t)                           # word tokenization
    t = [i for i in t if i not in sw]              # stop words removal
    t = [lm.lemmatize(i,pos="v") for i in t]       # lemmatization  # returns list of words
    t = " ".join(t)                                # Joining all the words
    data.append(t)
print(data)

['love echo', 'love', 'sometimes play game answer question correctly alexa say get wrong answer like able turn light away home', 'lot fun thing yr old learn dinosaurs control light play game like categories nice sound play music well', 'music', 'receive echo gift need another bluetooth something play music easily accessible find smart speaker wait see else', 'without cellphone use many feature ipad see use great alarm u r almost deaf hear alarm bedroom live room reason enough keep fun ask random question hear response seem smartbon politics yet', 'think th one purchase work get one every room house really like feature offer specifily play music echo control light throughout house', 'look great', 'love listen songs hear since childhood get news weather information great', 'send year old dad talk constantly', 'love learn know things eveyday still figure everything work far easy use understand make laugh time', 'purchase mother knee problems give something try come get around fast like en

In [9]:
cv=CountVectorizer()

In [10]:
sm=cv.fit_transform(data).toarray()
print(sm)
print(cv.get_feature_names_out())
print(len(cv.get_feature_names_out()))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['abay' 'abc' 'abd' ... 'zonked' 'zzzz' 'zzzzzzz']
3086


In [11]:
df2=pd.DataFrame(sm,columns=cv.get_feature_names_out())
df2.head()

abay  abc  abd  abide  abilities  ability  able  absolutely  absolutly  ac  \
0     0    0    0      0          0        0     0           0          0   0   
1     0    0    0      0          0        0     0           0          0   0   
2     0    0    0      0          0        0     1           0          0   0   
3     0    0    0      0          0        0     0           0          0   0   
4     0    0    0      0          0        0     0           0          0   0   

   ...  youngest  youtube  yr  yrs  yup  zero  zigbee  zonked  zzzz  zzzzzzz  
0  ...         0        0   0    0    0     0       0       0     0        0  
1  ...         0        0   0    0    0     0       0       0     0        0  
2  ...         0        0   0    0    0     0       0       0     0        0  
3  ...         0        0   1    0    0     0       0       0     0        0  
4  ...         0        0   0    0    0     0       0       0     0        0  

[5 rows x 3086 columns]

In [12]:
df3 = pd.DataFrame (data, columns = ['reviews'])
df['reviews']=df3['reviews']
df

reviews  sentiment
0                                             love echo          1
1                                                  love          1
2     sometimes play game answer question correctly ...          1
3     lot fun thing yr old learn dinosaurs control l...          1
4                                                 music          1
...                                                 ...        ...
3145                        perfect kid adults everyone          1
3146  listen music search locations check time look ...          1
3147  love things run entire home tv light thermosta...          1
3148  complaint sound quality great mostly use comma...          1
3149                                               good          1

[3150 rows x 2 columns]

In [13]:
x = cv.fit_transform(data).toarray()
y = df.iloc[:, 1].values

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(2362, 3086)
(788, 3086)
(2362,)
(788,)


In [15]:
m2=LogisticRegression();
m2.fit(x_train,y_train)

LogisticRegression()

In [16]:
print('training score',m2.score(x_train,y_train))
print('testing score',m2.score(x_test,y_test))

training score 0.9779847586790855
testing score 0.9352791878172588


In [17]:
ypred_m2=m2.predict(x_test)
print(ypred_m2)

[1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [18]:
print('accuracy score=',accuracy_score(y_test,ypred_m2))

accuracy score= 0.9352791878172588


In [19]:
cm2=confusion_matrix(y_test,ypred_m2)
print(cm2)
print(classification_report(y_test,ypred_m2))

[[ 25  41]
 [ 10 712]]
              precision    recall  f1-score   support

           0       0.71      0.38      0.50        66
           1       0.95      0.99      0.97       722

    accuracy                           0.94       788
   macro avg       0.83      0.68      0.73       788
weighted avg       0.93      0.94      0.93       788



In [20]:
m3=KNeighborsClassifier(n_neighbors=12)
m3.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=12)

In [21]:
print('Training score=',m3.score(x_train,y_train))
print('Testing score=',m3.score(x_test,y_test))

C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Training score= 0.9204064352243861
Testing score= 0.9175126903553299


C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [22]:
ypred_m3=m3.predict(x_test)
print(ypred_m3)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [23]:
cm3=confusion_matrix(y_test,ypred_m3)
print(cm3)
print(classification_report(y_test,ypred_m3))

[[  1  65]
 [  0 722]]
              precision    recall  f1-score   support

           0       1.00      0.02      0.03        66
           1       0.92      1.00      0.96       722

    accuracy                           0.92       788
   macro avg       0.96      0.51      0.49       788
weighted avg       0.92      0.92      0.88       788



In [24]:
print('accuracy score=',accuracy_score(y_test,ypred_m3))

accuracy score= 0.9175126903553299


In [25]:
m1=MultinomialNB();

In [31]:
m1.fit(x_train,y_train)

MultinomialNB()

In [27]:
print('Training score=',m1.score(x_train,y_train))
print('Testing score=',m1.score(x_test,y_test))

Training score= 0.95385266723116
Testing score= 0.932741116751269


In [28]:
ypred_m1=m1.predict(x_test)
print(ypred_m1)

[1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [29]:
print('accuracy score=',accuracy_score(y_test,ypred_m1))

accuracy score= 0.932741116751269


In [30]:
cm1=confusion_matrix(y_test,ypred_m1)
print(cm1)
print(classification_report(y_test,ypred_m1))

[[ 22  44]
 [  9 713]]
              precision    recall  f1-score   support

           0       0.71      0.33      0.45        66
           1       0.94      0.99      0.96       722

    accuracy                           0.93       788
   macro avg       0.83      0.66      0.71       788
weighted avg       0.92      0.93      0.92       788

