In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('C:\\Users\\dell\\OneDrive\\Desktop\\e7\\mobile_price_range_data.csv')

In [3]:
df.head(10)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   
5           1859     0          0.5         1   3       0          22    0.7   
6           1821     0          1.7         0   4       1          10    0.8   
7           1954     0          0.5         1   0       0          24    0.8   
8           1445     1          0.5         0   0       0          53    0.7   
9            509     1          0.6         1   2       1           9    0.1   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   
5        164        1  ...       1004      1654  1067    17     1         10   
6        139        8  ...        381      1018  3220    13     8         18   
7        187        4  ...        512      1149   700    16     3          5   
8        174        7  ...        386       836  1099    17     1         20   
9         93        5  ...       1137      1224   513    19    10         12   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  
5        1             0     0            1  
6        1             0     1            3  
7        1             1     1            0  
8        1             0     0            0  
9        1             0     0            0  

[10 rows x 21 columns]

In [4]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [5]:
y=df['price_range']
x=[['ram']]
print(type(x))
print(type(y))

<class 'list'>
<class 'pandas.core.series.Series'>


In [6]:
df.dtypes

battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
price_range        int64
dtype: object

In [7]:
df['price_range'].value_counts()

1    500
2    500
3    500
0    500
Name: price_range, dtype: int64

In [8]:
x1=df.drop('price_range',axis=1)
y1=df['price_range']

In [9]:
print(x1.shape)
print(y1.shape)

(2000, 20)
(2000,)


### Splitting into Training and Testing data

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x1,y1,test_size=0.40,random_state=0)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1200, 20)
(800, 20)
(1200,)
(800,)


In [11]:
x_train.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
891            1652     0          0.6         1   4       1          40   
1796            793     1          2.8         1   1       1          64   
1868           1766     1          0.5         1   1       1          22   
1042           1674     0          2.8         1   0       1          52   
996             774     0          0.5         1   2       1          10   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
891     1.0        198        7   6        352      1084  3592     7     6   
1796    0.4        179        4   2        818      1006  2296    12     0   
1868    0.8        122        8   4        291      1318  3297     7     5   
1042    0.2         89        3   7       1432      1649  2030     7     0   
996     0.5        188        2   9       1480      1731  2944     8     6   

      talk_time  three_g  touch_screen  wifi  
891           6        1             0     0  
1796          5        1             1     0  
1868         16        1             0     0  
1042          6        1             0     0  
996           2        1             1     1

In [12]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

## Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
m1=LogisticRegression()
m1.fit(x_train,y_train)

C:\Users\dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
print('training score',m1.score(x_train,y_train))
print('testing score',m1.score(x_test,y_test))

training score 0.63
testing score 0.645


### Predicting price range

In [16]:
ypred_m1=m1.predict(x_test)
print(ypred_m1)

[3 0 2 1 3 0 0 2 3 2 1 3 1 1 2 0 3 2 2 1 0 0 3 1 1 2 3 1 3 1 2 0 1 1 2 3 0
 0 3 2 3 3 3 3 2 2 0 1 3 1 0 2 0 2 0 3 3 1 0 3 3 2 2 1 1 3 3 3 2 2 3 2 1 0
 1 3 3 1 1 1 3 1 3 0 0 0 1 0 1 3 1 2 1 0 0 3 2 3 0 2 1 2 2 0 3 2 3 2 3 3 2
 0 0 2 3 3 1 0 1 0 0 3 2 3 1 2 0 0 0 3 1 3 3 2 3 3 3 3 0 1 1 3 2 3 1 3 0 0
 2 0 1 1 1 1 3 0 0 3 1 3 2 2 2 1 3 3 3 3 0 1 3 2 1 3 3 0 1 1 3 0 3 1 0 1 3
 1 2 0 3 3 3 3 1 1 2 1 0 3 2 0 3 3 3 0 1 3 2 2 0 0 0 2 2 3 0 0 0 2 2 2 2 3
 0 0 3 3 2 2 0 3 1 0 0 3 2 0 3 2 0 0 0 3 3 2 0 0 2 3 3 1 3 0 2 1 1 0 1 2 3
 2 1 0 1 3 3 3 2 3 3 2 1 2 2 2 1 3 2 2 2 1 0 2 1 0 0 0 1 3 3 3 0 1 2 0 2 2
 3 0 1 0 1 1 3 0 0 1 3 1 2 0 1 1 3 0 2 3 2 2 0 1 3 1 0 1 0 1 0 3 1 2 2 0 0
 2 3 0 3 1 1 0 1 3 0 2 1 1 2 3 2 0 3 0 0 3 1 3 3 2 2 0 3 2 3 2 3 2 2 3 3 0
 2 0 1 0 1 1 2 2 1 3 1 1 0 1 1 3 1 0 0 3 0 3 0 2 3 1 1 0 2 1 0 0 3 0 3 3 0
 3 3 3 2 2 3 2 1 3 1 2 1 0 2 1 1 2 1 3 1 2 2 0 3 1 1 1 3 0 2 3 2 2 3 3 0 0
 1 2 1 2 0 3 3 0 3 3 0 3 1 2 0 2 2 0 3 3 2 0 2 0 3 3 2 1 1 3 1 2 0 0 1 3 0
 2 0 0 1 2 0 1 2 0 3 3 3 

### Accuracy Score for Logistic Regression

In [17]:
print('accuracy score=',accuracy_score(y_test,ypred_m1))
print('testing score=',m1.score(x_test,y_test))

accuracy score= 0.645
testing score= 0.645


### Confusion matrix and classification report

In [18]:
cm=confusion_matrix(y_test,ypred_m1)
print(cm)
print(classification_report(y_test,ypred_m1))

[[170  33   2   0]
 [ 30 102  44  11]
 [  0  50  86  63]
 [  0   2  49 158]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       205
           1       0.55      0.55      0.55       187
           2       0.48      0.43      0.45       199
           3       0.68      0.76      0.72       209

    accuracy                           0.65       800
   macro avg       0.64      0.64      0.64       800
weighted avg       0.64      0.65      0.64       800



In [19]:
m=m1.coef_
c=m1.intercept_
print(m)
print(c)

[[-6.42840937e-04  3.58797698e-04  1.05822315e-03  3.20316246e-04
   1.83229863e-03  2.53510917e-04  1.36126767e-02  2.09803664e-04
   4.42036566e-02  3.07554878e-03  5.36157617e-03 -1.45085982e-03
   8.47162866e-04 -3.93554911e-03  7.80437204e-03  3.94849747e-03
   6.63579002e-03  3.38940391e-04  3.51337379e-04  2.89362858e-04]
 [ 9.87186410e-05  7.46280558e-05  2.23029186e-04  1.81878311e-04
   7.86233510e-04  3.08335702e-04  6.14770804e-03  1.93600640e-04
   1.21143993e-02 -7.95524645e-04  2.15338185e-03 -2.88838923e-04
   5.02187901e-04 -6.63327425e-04  2.28532660e-03 -5.67208740e-04
   2.11951850e-03  2.88402919e-04  1.47322518e-04  1.19964643e-04]
 [ 2.83217587e-04 -4.63030822e-05 -2.51294876e-04 -1.10348620e-04
   6.43526714e-04 -2.83792351e-04 -6.67048280e-03 -1.15631267e-04
  -1.42483476e-02  5.33709859e-04 -4.86290315e-04  3.05715507e-04
  -2.39281308e-04  1.49143953e-03 -2.48257035e-03  7.32349118e-04
  -1.81300833e-03 -1.89615710e-04 -1.95131678e-04 -3.97744875e-05]
 [ 2.60

In [20]:
def sigmoid(m,x,c):
    m=np.array(m)
    x=np.array(x)
    c=np.expand_dims(c,axis=-1)
    res=1/(1+np.exp(-(m*x+c)))
    print(res)

In [21]:
ypredram1=(m1.predict([[357,0,2.7,1,1,0,9,1,837,7,5,1732,1920,4579,13,17,13,1,0,1]]))
print(ypredram1)
sigmoid(m,[[357,0,2.7,1,1,0,9,1,837,7,5,1732,1920,4579,13,17,13,1,0,1]],c)

[0]
[[4.43029199e-01 5.00154270e-01 5.00868569e-01 5.00234349e-01
  5.00612344e-01 5.00154270e-01 5.30743959e-01 5.00206721e-01
  1.00000000e+00 5.05536254e-01 5.06855810e-01 7.50023236e-02
  8.35781558e-01 1.49244903e-08 5.25496345e-01 5.16928911e-01
  5.21706934e-01 5.00239005e-01 5.00154270e-01 5.00226610e-01]
 [5.08848049e-01 5.00038334e-01 5.00188878e-01 5.00083803e-01
  5.00234892e-01 5.00038334e-01 5.13867120e-01 5.00086734e-01
  9.99960529e-01 4.98646169e-01 5.02730034e-01 3.77513484e-01
  7.23992722e-01 4.57723119e-02 5.07465090e-01 4.97627714e-01
  5.06926326e-01 5.00110434e-01 5.00038334e-01 5.00068325e-01]
 [5.25228645e-01 4.99972918e-01 4.99803294e-01 4.99945331e-01
  5.00133800e-01 4.99972918e-01 4.84968862e-01 4.99944010e-01
  6.61624939e-06 5.00906909e-01 4.99365055e-01 6.29341045e-01
  3.87097697e-01 9.98919438e-01 4.91905272e-01 5.03085363e-01
  4.94080917e-01 4.99925514e-01 4.99972918e-01 4.99962974e-01]
 [5.23103760e-01 4.99834479e-01 4.99139258e-01 4.99736517e-01
 

C:\Users\dell\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


## KNN Classification

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
m2=KNeighborsClassifier(n_neighbors=10)
m2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [24]:
print('Training score=',m2.score(x_train,y_train))
print('Testing score=',m2.score(x_test,y_test))

Training score= 0.9433333333333334
Testing score= 0.93125


C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims`

### Predicted price

In [25]:
ypred_m2=m2.predict(x_test)
print(ypred_m2)

[3 0 2 2 3 0 0 2 3 1 0 3 0 2 3 0 3 2 2 1 0 0 3 1 2 2 3 1 3 1 1 0 2 0 1 3 0
 0 3 3 3 1 3 3 1 3 0 1 3 1 1 3 0 3 0 2 2 2 0 2 3 1 3 2 1 2 3 2 1 2 3 2 1 0
 1 3 2 1 1 2 3 3 3 0 0 0 2 0 2 3 1 2 2 0 0 3 2 3 0 3 1 1 2 1 3 2 2 3 2 3 3
 0 0 1 2 3 0 0 1 0 0 3 2 2 1 1 1 1 0 2 1 3 3 3 3 3 3 2 0 1 1 2 1 3 0 3 0 0
 2 0 1 1 1 1 3 0 0 3 1 3 2 1 3 1 2 3 3 2 1 0 3 1 2 3 3 0 2 2 3 0 2 1 0 1 2
 1 2 0 2 3 1 1 0 2 3 0 1 2 2 0 3 3 3 1 2 3 3 3 0 0 0 2 3 3 0 0 1 3 1 3 3 3
 0 0 2 2 3 1 0 2 0 0 0 3 3 0 2 2 1 1 0 3 3 3 0 0 1 3 3 2 3 0 3 1 1 0 2 3 2
 2 0 0 1 2 3 2 2 3 1 1 0 3 3 2 1 3 3 2 2 1 0 2 2 1 0 0 2 2 2 2 0 1 3 0 1 2
 3 0 2 0 1 1 3 0 0 1 3 1 2 0 2 0 3 0 3 3 2 3 1 2 2 1 1 1 0 1 0 3 1 0 3 0 0
 1 2 0 3 1 2 0 1 3 0 2 2 1 2 1 1 0 2 0 0 3 1 2 3 2 2 0 3 2 2 1 3 2 3 3 3 0
 2 0 3 0 1 1 2 2 1 3 1 2 0 1 2 3 0 0 1 3 0 3 0 1 2 1 1 0 3 1 0 1 3 0 3 3 0
 2 1 3 1 1 3 2 0 3 3 2 0 0 3 0 1 1 1 3 2 3 2 0 3 0 0 1 3 0 0 3 3 2 2 3 0 0
 1 2 1 2 0 3 3 0 2 3 0 2 2 1 0 2 2 1 3 2 2 0 2 0 3 3 2 1 0 3 0 2 0 0 1 3 0
 3 0 0 1 2 0 1 3 0 2 2 1 

C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


### Confusion Matrix and Classification Report

In [26]:
cm2=confusion_matrix(y_test,ypred_m2)
print(cm2)
print(classification_report(y_test,ypred_m2))

[[205   0   0   0]
 [ 11 172   4   0]
 [  0  14 176   9]
 [  0   0  17 192]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.97       205
           1       0.92      0.92      0.92       187
           2       0.89      0.88      0.89       199
           3       0.96      0.92      0.94       209

    accuracy                           0.93       800
   macro avg       0.93      0.93      0.93       800
weighted avg       0.93      0.93      0.93       800



### Accuracy Score

In [27]:
print('acuracy score=',accuracy_score(y_test,ypred_m2))
print('Testing score=',m2.score(x_test,y_test))

acuracy score= 0.93125
Testing score= 0.93125


C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


## SVM Classifier with Linear

In [28]:
from sklearn.svm import SVC

In [29]:
m3=SVC(kernel='linear',C=1)
m3.fit(x_train,y_train)

SVC(C=1, kernel='linear')

In [30]:
print('training score=',m3.score(x_train,y_train))
print('testing score=',m3.score(x_test,y_test))

training score= 0.9975
testing score= 0.97375


### Predicted price

In [31]:
ypred_m3=m3.predict(x_test)
print(ypred_m3)

[3 0 2 2 2 0 0 3 3 1 1 3 0 2 3 0 3 2 2 1 0 0 3 1 2 2 3 1 3 1 1 0 2 0 1 3 0
 0 3 3 2 1 3 3 1 3 0 1 3 1 1 3 0 3 0 2 2 2 0 3 3 1 3 2 1 2 3 2 2 2 3 2 1 0
 1 3 2 2 1 2 3 3 3 0 0 0 2 1 2 3 1 2 2 1 0 3 3 3 0 3 1 1 3 2 3 2 2 3 2 3 3
 0 0 1 3 3 0 0 1 0 0 3 2 2 1 2 1 1 0 2 1 3 3 3 3 3 3 2 0 1 1 2 1 3 1 3 0 0
 2 0 1 1 1 1 3 0 0 3 1 3 2 1 3 1 2 3 3 2 1 0 3 1 1 3 3 0 2 2 3 0 2 1 0 1 2
 1 2 0 3 3 1 1 0 2 3 0 1 3 2 0 3 3 3 1 2 3 3 3 0 0 0 2 3 3 0 0 1 3 2 3 3 3
 0 0 2 2 3 1 0 2 0 0 0 3 2 0 2 2 1 1 0 2 3 3 0 0 1 3 3 2 3 0 3 1 1 0 2 3 3
 2 0 0 1 2 3 2 2 3 2 1 0 3 3 2 1 3 2 2 2 1 0 2 2 1 0 0 2 2 2 2 0 1 3 0 2 2
 3 0 2 0 1 1 3 0 0 2 3 1 2 0 2 0 3 0 3 3 2 3 1 2 2 1 1 1 0 1 0 3 1 0 3 0 0
 1 3 0 3 1 1 0 1 3 0 2 2 1 2 1 1 0 2 0 0 3 1 2 3 2 2 0 3 2 2 1 3 2 3 3 3 0
 2 0 3 0 1 1 2 2 1 3 1 2 0 1 2 3 0 0 1 3 0 3 0 2 2 1 1 0 2 0 0 1 3 0 3 3 0
 2 1 3 1 1 3 2 0 3 2 2 0 0 3 0 1 1 1 3 2 3 2 0 3 0 0 1 3 0 0 3 2 2 2 3 0 0
 1 2 1 2 0 3 3 0 3 3 0 2 2 1 0 2 2 1 3 2 2 0 2 0 3 3 2 1 0 3 1 2 0 0 1 3 0
 3 0 0 1 2 0 1 3 0 2 2 1 

### Confusion Matrix and Classification Report

In [32]:
cm3=confusion_matrix(y_test,ypred_m3)
print(cm3)
print(classification_report(y_test,ypred_m3))

[[205   0   0   0]
 [  5 178   4   0]
 [  0   4 191   4]
 [  0   0   4 205]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       205
           1       0.98      0.95      0.96       187
           2       0.96      0.96      0.96       199
           3       0.98      0.98      0.98       209

    accuracy                           0.97       800
   macro avg       0.97      0.97      0.97       800
weighted avg       0.97      0.97      0.97       800



### Accuracy Score

In [33]:
print('accuracy score=',accuracy_score(y_test,ypred_m3))
print('testing score=',m3.score(x_test,y_test))

accuracy score= 0.97375
testing score= 0.97375


## SVM Classifier with rbf Kernel

In [34]:
m4=SVC(kernel='rbf',C=10,gamma=10)

In [35]:
m4.fit(x_train,y_train)

SVC(C=10, gamma=10)

In [36]:
print('training score=',m4.score(x_train,y_train))
print('testing score=',m4.score(x_test,y_test))

training score= 1.0
testing score= 0.23375


### Predicted price

In [37]:
ypred_m4=m4.predict(x_test)
print(ypred_m4)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

### Confusion Matrix and Classification Report

In [38]:
cm4=confusion_matrix(y_test,ypred_m4)
print(cm4)
print(classification_report(y_test,ypred_m4,zero_division=0))

[[  0 205   0   0]
 [  0 187   0   0]
 [  0 199   0   0]
 [  0 209   0   0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       205
           1       0.23      1.00      0.38       187
           2       0.00      0.00      0.00       199
           3       0.00      0.00      0.00       209

    accuracy                           0.23       800
   macro avg       0.06      0.25      0.09       800
weighted avg       0.05      0.23      0.09       800



### Accuracy Score

In [39]:
print('accuracy score=',accuracy_score(y_test,ypred_m4))
print('testing score=',m4.score(x_test,y_test))

accuracy score= 0.23375
testing score= 0.23375


## The Best Accuracy Scored model is SVM when kernel is Linear 

In [40]:
print(ypred_m3)

[3 0 2 2 2 0 0 3 3 1 1 3 0 2 3 0 3 2 2 1 0 0 3 1 2 2 3 1 3 1 1 0 2 0 1 3 0
 0 3 3 2 1 3 3 1 3 0 1 3 1 1 3 0 3 0 2 2 2 0 3 3 1 3 2 1 2 3 2 2 2 3 2 1 0
 1 3 2 2 1 2 3 3 3 0 0 0 2 1 2 3 1 2 2 1 0 3 3 3 0 3 1 1 3 2 3 2 2 3 2 3 3
 0 0 1 3 3 0 0 1 0 0 3 2 2 1 2 1 1 0 2 1 3 3 3 3 3 3 2 0 1 1 2 1 3 1 3 0 0
 2 0 1 1 1 1 3 0 0 3 1 3 2 1 3 1 2 3 3 2 1 0 3 1 1 3 3 0 2 2 3 0 2 1 0 1 2
 1 2 0 3 3 1 1 0 2 3 0 1 3 2 0 3 3 3 1 2 3 3 3 0 0 0 2 3 3 0 0 1 3 2 3 3 3
 0 0 2 2 3 1 0 2 0 0 0 3 2 0 2 2 1 1 0 2 3 3 0 0 1 3 3 2 3 0 3 1 1 0 2 3 3
 2 0 0 1 2 3 2 2 3 2 1 0 3 3 2 1 3 2 2 2 1 0 2 2 1 0 0 2 2 2 2 0 1 3 0 2 2
 3 0 2 0 1 1 3 0 0 2 3 1 2 0 2 0 3 0 3 3 2 3 1 2 2 1 1 1 0 1 0 3 1 0 3 0 0
 1 3 0 3 1 1 0 1 3 0 2 2 1 2 1 1 0 2 0 0 3 1 2 3 2 2 0 3 2 2 1 3 2 3 3 3 0
 2 0 3 0 1 1 2 2 1 3 1 2 0 1 2 3 0 0 1 3 0 3 0 2 2 1 1 0 2 0 0 1 3 0 3 3 0
 2 1 3 1 1 3 2 0 3 2 2 0 0 3 0 1 1 1 3 2 3 2 0 3 0 0 1 3 0 0 3 2 2 2 3 0 0
 1 2 1 2 0 3 3 0 3 3 0 2 2 1 0 2 2 1 3 2 2 0 2 0 3 3 2 1 0 3 1 2 0 0 1 3 0
 3 0 0 1 2 0 1 3 0 2 2 1 